ecommerce_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: 'my-etl-project-434409'
      dataset: 'etl_dataset'
      keyfile:  "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      threads: 4
      timeout_seconds: 300
      location: 'US'
      priority: 'interactive'
